codes = {
    '+ de 3 SVB y eq. Sanit.': 'MAS_3_SVB_EQ_SANITARIOS',
    '1 o + SVB y 1 o + SVA': 'UNO_O_MAS_SVB_UNO_O_MAS_SVA',
    '1 o + SVB y 1 o + SVA y PMA': 'UNO_O_MAS_SVB_UNO_O_MAS_SVA_PMA',
    '1 SVB': 'UNO_SVB',
    'Acc. Trasp. Merc. Peligrosas': 'ACC_TPTE_MERCANCIAS_PELIGROSAS',
    'Accidente con 3 o más víctimas confirmadas': 'ACC_TRES_O_MAS_VICTIMAS_CONFIRMADAS',
    'Accidente con vehículo pesado': 'ACC_VEHICULO_PESADO',
    'Accidente de autobús / autocar': 'ACC_AUTOBUS',
    'Accidente de avión': 'ACC_AVION',
    'Accidente de bicicleta': 'ACC_BICICLETA',
    'Accidente de monopatin': 'ACC_MONOPATIN',
    'Accidente de motocicleta': 'ACC_MOTOCICLETA',
    'Accidente de tren': 'ACC_TREN',
    'Accidente menos de 3 victimas': 'ACC_MENOS_3_VICTIMAS',
    'Accidente sin especificar': 'ACC_SIN_ESPECIFICAR',
    'Agresión con spray de defensa': 'AGRESION_SPRAY_DEFENSA',
    'Agresión sexual': 'AGRESION_SEXUAL',
    'Agresión sin especificar': 'AGRESION_SIN_ESPECIFICAR',
    'Ahogado': 'AHOGADO',
    'Apertura de puerta': 'APERTURA_PUERTA',
    'Arma blanca': 'ARMA_BLANCA',
    'Arma de fuego': 'ARMA_FUEGO',
    'Arrollamiento metro y/o tren': 'ARROLLAMIENTO_METRO_TREN',
    'Atención psicológica a Familiares y allegados': 'ATENC_PSICOLOGICA_FAMILIARES_ALLEGADOS',
    'Atención psicológica a Implicados.': 'ATENC_PSICOLOGICA_IMPLICADOS',
    'Atención psicológica a intervinientes de Bomberos.': 'ATENC_PSICOLOGICA_BOMBEROS',
    'Atención psicológica a intervinientes de Cuerpos de Seguridad': 'ATENC_PSICOLOGICA_CUERPOS_SEGURIDAD',
    'Atención psicológica a intervinientes de SAMUR-PC.': 'ATENC_PSICOLOGICA_SAMUR_PC',
    'Atención psicológica a la Víctima primaria': 'ATENC_PSICOLOGICA_VICTIMA_PRIMARIA',
    'Atención psicológica a Testigos.': 'ATENC_PSICOLOGICA_TESTIGOS',
    'Atrapamientos/enterramientos': 'ATRAPAMIENTO_ENTERRAMIENTO',
    'Atropello': 'ATROPELLO',
    'Autolisis no traumática': 'AUTOLISIS_NO_TRAUMATICA',
    'Autolisis traumática': 'AUTOLISIS_TRAUMATICA',
    'Bombero de Madrid': 'BOMBERO_MADRID',
    'Casual: caída, etc': 'CASUAL_CAIDA_ETC',
    'Certificación psiquiátrico': 'CERTIFICACION_PSIQUIATRICO',
    'Colaboración del FOXTROP en una actuación': 'COLABORACION_FOXTROP_ACTUACION',
    'Convulsión y/o epilepsia': 'CONVULSION_EPILEPSIA',
    'Derrumbamientos': 'DERRUMBAMIENTOS',
    'Determinación de PCR (covid 19) en casos excepcionales': 'DETERMINACION_PCR_COVID_19_EXCEPCIONALES',
    'Diabético': 'DIABETICO',
    'Domicilio': 'DOMICILIO',
    'Electrocutado': 'ELECTROCUTADO',
    'Explosión': 'EXPLOSION',
    'Hasta 3 SVB': 'HASTA_3_SVB',
    'Heridas': 'HERIDAS',
    'Heridas complicadas': 'HERIDAS_COMPLICADAS',
    'Incendio': 'INCENDIO',
    'Incendio con Victimas confirmadas': 'INCENDIO_VICTIMAS_CONFIRMADAS',
    'Inconsciente sin filiar causa': 'INCONSCIENTE_SIN_FILIAR_CAUSA',
    'Infarto o patología coronaria': 'INFARTO_PATOLOGIA_CORONARIA',
    'Intoxicación etílica': 'INTOXICACION_ETILICA',
    'Intoxicación por fármacos y/o productos tóxicos': 'INTOXICACION_FARMACOS_PRODUCTOS_TOXICOS',
    'Local público (centro sanita.)': 'LOCAL_PUBLICO_CENTRO_SANITARIO',
    'Maltrato a ancianos': 'MALTRATO_ANCIANOS',
    'Maltrato a menores': 'MALTRATO_MENORES',
    'No suceso': 'NO_SUCESO',
    'Orden judicial': 'ORDEN_JUDICIAL',
    'Orden medica': 'ORDEN_MEDICA',
    'Orden médica urgente /agresivo': 'ORDEN_MEDICA_URGENTE_AGRESIVO',
    'Otras instituciones': 'OTRAS_INSTITUCIONES',
    'Otros': 'OTROS',
    'Paciente en huelga de hambre': 'PACIENTE_HUELGA_HAMBRE',
    'Pacientes en RCP prolongada': 'PACIENTES_RCP_PROLONGADA',
    'Parada Cardiorespiratoria': 'PARADA_CARDIORESPIRATORIA',
    'Patología anafiláctica': 'PATOLOGIA_ANAFILACTICA',
    'Patología cardiovascular': 'PATOLOGIA_CARDIOVASCULAR',
    'Patología digestiva': 'PATOLOGIA_DIGESTIVA',
    'Patología ginecológica': 'PATOLOGIA_GINECOLOGICA',
    'Patología infecciosa': 'PATOLOGIA_INFECCIOSA',
    'Patología neurológica': 'PATOLOGIA_NEUROLOGICA',
    'Patología obstétrica': 'PATOLOGIA_OBSTETRICA',
    'Patología psicosomática': 'PATOLOGIA_PSICOSOMATICA',
    'Patología respiratoria': 'PATOLOGIA_RESPIRATORIA',
    'Patología urológica': 'PATOLOGIA_UROLOGICA',
    'Persona “sin techo” fallecida en vía pública': 'PERSONA_SIN_TECHO_FALLECIDA_VIA_PUBLICA',
    'Policía municipal': 'POLICIA_MUNICIPAL',
    'Policía nacional': 'POLICIA_NACIONAL',
    'Precipitado': 'PRECIPITADO',
    'Preventivos': 'PREVENTIVOS',
    'Problema social': 'PROBLEMA_SOCIAL',
    'Quemado': 'QUEMADO',
    'Riesgo biológico': 'RIESGO_BIOLOGICO',
    'Riesgo nuclear': 'RIESGO_NUCLEAR',
    'Riesgo público': 'RIESGO_PUBLICO',
    'Riesgo químico': 'RIESGO_QUIMICO',
    'SAMUR': 'SAMUR',
    'Serv. Preventivo desde oper. Ordinario': 'SERV_PREVENTIVO_OPER_ORDINARIO',
    'Servicios de análisis de riesgos': 'SERVICIOS_ANALISIS_RIESGOS',
    'Servicios de seguimiento de riesgos': 'SERVICIOS_SEGUIMIENTO_RIESGOS',
    'Servicios especiales': 'SERVICIOS_ESPECIALES',
    'Sobredosis': 'SOBREDOSIS',
    'Sumisión Química': 'SUMISION_QUIMICA',
    'Todos los medios de SAMUR-PC': 'TODOS_SAMUR_PC',
    'Vía publica': 'VIA_PUBLICA',
    'Violencia de genero': 'VIOLENCIA_GENERO'
 }

hospitals = {
    "Concepción (Fund. J. Díaz)": "FUND_JIMENEZ_DIAZ",
    "Doce de Octubre": "DOCE_DE_OCTUBRE",
    "Clínico San Carlos": "CLINICO_SAN_CARLOS",
    "INFANTA LEONOR": "INFANTA_LEAONOR",
    "Gregorio Marañón": "GREGORIO_MARANON",
    "Central de la Defensa": "CENTRAL_DE_LA_DEFENSA",
    "Ramón y Cajal": "RAMON_Y_CAJAL",
    "La Paz": "LA_PAZ",
    "La Princesa": "LA_PRINCESA",
    "Niño Jesús (Infantil)": "NINO_JESUS",
    "Getafe": "GETAFE",
    "Doctor Rodriguez Lafora": "DOCTOR_RODRIGUEZ_LAFORA",
    "Centros Municipales (Asist. y  Albergues)": "CENTROS_MINICIPALES",
    "SANTA CRISTINA": "SANTA_CRISTINA",
    "Otros Centros Públicos": "OTROS_CENTROS_PUBLICOS",
    "Puerta de Hierro": "PUERTA_DE_HIERRO",
    "VIRGEN DE LA TORRE": "VIRGEN_DE_LA_TORRE"
}

districts = {
    "CENTRO": "CENTRO",
    "CARABANCHEL": "CARABANCHEL",
    "SALAMANCA": "SALAMANCA",
    "VILLA DE VALLECAS": "VILLA_DE_VALLECAS",
    "TETUAN": "TETUAN",
    "VALLECAS PTE.": "VALLECAS_PTE",
    "LATINA": "LATINA",
    "MORATALAZ": "MORATALAZ",
    "VILLAVERDE": "VILLAVERDE",
    "SAN BLAS": "SAN_BLAS",
    "CIUDAD LINEAL": "CIUDAD_LINEAL",
    "MONCLOA": "MONCLOA",
    "CHAMBERI": "CHAMBERI",
    "CHAMARTIN": "CHAMARTIN",
    "USERA": "USERA",
    "HORTALEZA": "HORTALEZA",
    "BARAJAS": "BARAJAS",
    "ARGANZUELA": "ARGANZUELA",
    "RETIRO": "RETIRO",
    "FUENCARRAL": "FUENCARRAL",
    "VICALVARO": "VICALVARO",
    "POZUELO": "POZUELO",
    "FUERA TERMINO MUNICIPAL": "FUERA_TERMINO_MUNICIPAL",
    "CARRETERAS Y CIRCUNVALACIONES": "CARRETERAS_Y_CIRCUNVALACIONES"
}